Fixed module path issue
os-fpga/rapid_power_estimator pull request #18
Opened 2024-02-22 03:55 UTC by GuanYung

This PR fixed the following error
ModuleNotFoundError: No module named 'backend'

2024-02-22 06:30 UTC, ravikiranchollangi requested changes
Please look at this: https://docs.python.org/3/reference/import.html#package-relative-imports

2024-02-22 06:31 UTC, ravikiranchollangi reviewed
Two comments.

2024-02-23 00:52 UTC, GuanYung commented on backend/restapi_server.py
> +print(str(path.parent.absolute()))
the print statement is removed now. I was using it for debugging.

2024-02-23 00:56 UTC, GuanYung commented on backend/restapi_server.py
> +
all the files was using the `from backend.submodule......` import statements
I was finding solution to fix the issue. At least for now it is an workaround. I need to learn more details about the import package/module in Python. Until then, I will find a proper fix.

below is the print out of command `npm start` for your reference

<img width="910" alt="image" src="https://github.com/os-fpga/rapid_power_estimator/assets/10010840/2400111f-5f0e-43b8-9cc8-ee3c07294eae">

2024-02-23 00:59 UTC, GuanYung commented
@ravikiranchollangi 
As at now, this is what I have. If you believe there is a better solution, I will need more time to figure out. 
Let me know if this PR works or you want a perfect fix for this issue.

2024-02-26 00:53 UTC, closed without merging