Define DSP Module API with Swagger/OpenAPI annotation
os-fpga/rapid_power_estimator pull request #74
Opened 2024-05-08 02:15 UTC by chernyee

This PR defines the DSP Module API using Swagger / OpenAPI annotation. With this API annotation defined, the integrated Swagger UI will be able to show the proper parameter text boxes and request/response JSON data models that user can use to test the API at the UI immediately.

2024-05-09 08:24 UTC, volodymyrkochyn approved these changes

2024-05-10 05:13 UTC, ravikiranchollangi commented
This is failing Mac OS, please address this.

2024-05-10 05:16 UTC, ravikiranchollangi requested changes
Please look at the Mac OS CI

2024-05-10 11:09 UTC, chernyee commented
> Please look at the Mac OS CI



> Please look at the Mac OS CI



> Please look at the Mac OS CI

![image](https://github.com/os-fpga/rapid_power_estimator/assets/12110149/973d2c6d-dc51-4e18-b7a6-c3c0e2743b24)

2024-05-10 16:41 UTC, ravikiranchollangi approved these changes

2024-05-10 16:42 UTC, merged